spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: http://localhost:8081
          predicates:
            - Path= /users/**
            
        - id: RATINGSERVICE
          uri: http://localhost:8083
          predicates:
            - Path=/ratings/**
            
        - id: HOTELSERVICE
          uri: http://localhost:8082
          predicates:
            - Path=/hotels/**,/staffs/**

server:
  port: 8085
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

