server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Vinit@985
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

